[package]
name = "glust-shader-process"
version = "0.1.0"
authors = ["Harri Hätinen <hhatinen@gmail.com>"]

[dependencies]
error-chain = "0.11.0"
syn = "0.11.11"
rustfmt = "0.9.0"
glutin = "*"
gl = "*"
libc = "*"
quote = "0.3.15"
glust = { git = "https://github.com/hnen/glust" }
